<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="2" total="7" passed="1" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[A/B Test Control]]>
    </line>
  </reporter-output>
  <suite started-at="2025-01-27T21:59:48 IST" name="All Test Suite" finished-at="2025-01-27T22:00:21 IST" duration-ms="32659">
    <groups>
    </groups>
    <test started-at="2025-01-27T21:59:48 IST" name="C:/InternetHerokuapp/InternetHerokuapp/src/test/java/test" finished-at="2025-01-27T22:00:21 IST" duration-ms="32659">
      <class name="test.IH_AB_Testing_Test">
        <test-method is-config="true" signature="Setup()[pri:0, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T21:59:48 IST" name="Setup" finished-at="2025-01-27T21:59:55 IST" duration-ms="6875" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="ABTesting_Test()[pri:1, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T21:59:55 IST" name="ABTesting_Test" finished-at="2025-01-27T21:59:55 IST" duration-ms="499" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[A/B Test Control]]>
            </line>
          </reporter-output>
        </test-method> <!-- ABTesting_Test -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T21:59:55 IST" name="teardown" finished-at="2025-01-27T21:59:56 IST" duration-ms="157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="Setup()[pri:0, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T21:59:56 IST" name="Setup" finished-at="2025-01-27T22:00:01 IST" duration-ms="5604" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method retried="true" signature="testFailure()[pri:2, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T22:00:01 IST" name="testFailure" finished-at="2025-01-27T22:00:01 IST" duration-ms="2" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Intentional Failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Intentional Failure
at org.testng.Assert.fail(Assert.java:111)
at test.IH_AB_Testing_Test.testFailure(IH_AB_Testing_Test.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFailure -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T22:00:01 IST" name="teardown" finished-at="2025-01-27T22:00:01 IST" duration-ms="159" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="Setup()[pri:0, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T22:00:01 IST" name="Setup" finished-at="2025-01-27T22:00:08 IST" duration-ms="6351" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="testFailure()[pri:2, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T22:00:08 IST" name="testFailure" finished-at="2025-01-27T22:00:08 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Intentional Failure]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Intentional Failure
at org.testng.Assert.fail(Assert.java:111)
at test.IH_AB_Testing_Test.testFailure(IH_AB_Testing_Test.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFailure -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T22:00:08 IST" name="teardown" finished-at="2025-01-27T22:00:08 IST" duration-ms="156" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="Setup()[pri:0, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T22:00:08 IST" name="Setup" finished-at="2025-01-27T22:00:14 IST" duration-ms="5553" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method retried="true" signature="testSkip()[pri:3, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T22:00:14 IST" name="testSkip" finished-at="2025-01-27T22:00:14 IST" duration-ms="4" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Skipping this test]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Skipping this test
at test.IH_AB_Testing_Test.testSkip(IH_AB_Testing_Test.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkip -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T22:00:14 IST" name="teardown" finished-at="2025-01-27T22:00:14 IST" duration-ms="160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="Setup()[pri:0, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T22:00:14 IST" name="Setup" finished-at="2025-01-27T22:00:20 IST" duration-ms="6525" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="testSkip()[pri:3, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T22:00:20 IST" name="testSkip" finished-at="2025-01-27T22:00:20 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Skipping this test]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Skipping this test
at test.IH_AB_Testing_Test.testSkip(IH_AB_Testing_Test.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkip -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:test.IH_AB_Testing_Test@5c86dbc5]" started-at="2025-01-27T22:00:20 IST" name="teardown" finished-at="2025-01-27T22:00:21 IST" duration-ms="224" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- test.IH_AB_Testing_Test -->
    </test> <!-- C:/InternetHerokuapp/InternetHerokuapp/src/test/java/test -->
  </suite> <!-- All Test Suite -->
</testng-results>
